base:
  dataset_type: "mscoco"
  dataset_config: 
    data_path: "./data/data/mscoco-text"
    positional_encoding_vectors: [[0, 0], [1, 0], [0, 1]]
    default_height: 64
    encode_absolute_position_norm: false
    encode_absolute_position_px: false
    encode_relative_position_norm: false
    encode_relative_position_px: false

  model_type: "sequence_stack"
  model_config:
    ## Stack settings
    n_layer: 2
    d_intermediate: 64
    skip_connection: true
    ## MAMBA settings
    mamba_d_model: 64
    mamba_d_state: 256
    mamba_d_conv: 4
    ## LSTM settings
    lstm_layer_idx: []
    lstm_d_hidden: 64

  optimizer_type: "adam"
  optimizer_config:
    lr: 0.001

  train_config:
    epochs: 2
    batch_size: 64

  val_config:
    batch_size: 64
    
cases: [{}]

