base:
  dataset_type: "mscoco"
  dataset_config: 
    data_path: "./data/data/mscoco-text"
    positional_encoding_vectors:
      - [1, 0]
      - [0, 1]
      - [2, 0]
      - [0, 2]
      - [4, 0]
      - [0, 4]
      - [8, 0]
      - [0, 8]
      - [16, 0]
      - [0, 16]
      - [32, 0]
      - [0, 32]
      - [64, 0]
      - [0, 64]
    default_height: 16
    encode_absolute_position_norm: true
    encode_absolute_position_px: false
    encode_relative_position_norm: true
    encode_relative_position_px: false

  model_type: "sequence_stack"
  model_config:
    ## Stack settings
    n_layer: 4
    d_intermediate: 128
    skip_connection: true
    ## MAMBA settings
    mamba_d_model: 256
    mamba_d_state: 256
    mamba_d_conv: 4
    ## LSTM settings
    lstm_layer_idx: []
    lstm_d_hidden: 64

  optimizer_type: "adam"
  optimizer_config:
    lr: 0.0001

  train_config:
    epochs: 20
    batch_size: 16

  val_config:
    batch_size: 16
    
cases: [{}]

