#!/bin/bash
#
# This script sets the Slurm configuration for tests.
#
# NOTE THAT THE OPTIONS HERE OVERRIDE THE OPTIONS IN THE JOB SCRIPT.

export SLURM_CONSTRAINT=sm_70
export SLURM_CPUS_PER_GPU=6  # Number of Cores per Task
export SLURM_GPUS=1  # Number of GPUs
export SLURM_MEM_PER_NODE=16384  # Requested Memory
export SLURM_PARTITION=gpu-preempt  # Partition
export SLURM_TIMELIMIT=04:00:00  # Job time limit
